using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Service.Biz.UiRestrictions.DAL.Migrations
{
    /// <inheritdoc />
    public partial class FillProducts : Migration
    {
        private const string Sql = @"INSERT INTO public.product(id, code, level) VALUES
(1, 'PlaziusBaseSingle', 1),
(2, 'PlaziusProSingle', 2),
(3, 'PlaziusMaxSingle', 3),
(4, 'PlaziusBaseNetwork', 1),
(5, 'PlaziusProNetwork', 2),
(6, 'PlaziusMaxNetwork', 3)
ON CONFLICT (id) DO UPDATE SET code=EXCLUDED.code;

INSERT INTO public.feature(id, name) VALUES
(1, 'pluzius_guests_app'),
(2, 'pluzius_guests_app_payment'),
(3, 'pluzius_guests_app_feedback'),
(4, 'pluzius_guests_app_preorder'),
(5, 'pluzius_guests_app_tips'),
(6, 'guest_base'),
(7, 'guest_base_import'),
(8, 'guest_card_add'),
(9, 'guest_card_delete'),
(10, 'guest_card_recover'),
(11, 'guest_card_edit'),
(12, 'guest_card_benefit'),
(13, 'guest_card_orders_history'),
(14, 'pluzius_guests_tg_bot'),
(15, 'pluzius_guests_wallet'),
(16, 'tag'),
(17, 'tag_add'),
(18, 'tag_delete'),
(19, 'tag_edit'),
(20, 'guest_base_tag_assignment'),
(21, 'guest_base_tag_delete'),
(22, 'guest_card_tag_assignment'),
(23, 'guest_base_tag_ab_divide'),
(24, 'tag_automatic'),
(25, 'tag_automatic_assignment'),
(26, 'stock_basic_tag_automatic_assignment'),
(27, 'stock_tag_trigger'),
(28, 'communications_tag_trigger'),
(29, 'reports_tag_filter_trigger'),
(30, 'communications'),
(31, 'communications_sms'),
(32, 'communications_mail'),
(33, 'communications_mail_constructor'),
(34, 'communications_wallet'),
(35, 'rank'),
(36, 'check_footer_guest_pl'),
(37, 'check_footer_guest_anonymous'),
(38, 'reports_feedback'),
(39, 'reports_operations_total'),
(40, 'reports_network_bonuses_balance'),
(41, 'reports_waiters_rating'),
(42, 'reports_guests_activity'),
(43, 'reports_cohort_analysis'),
(44, 'reports_ab_analysis'),
(45, 'reports_guests_privileges'),
(46, 'reports_restaurants_efficiency'),
(47, 'reports_stock_efficiency'),
(48, 'reports_rfm_common_values'),
(49, 'reports_rfm_guests'),
(50, 'dashboard_operational_sales'),
(51, 'dashboard_loyalty'),
(52, 'dashboard_preorder'),
(53, 'dashboard_wallet'),
(54, 'dashboard_trends'),
(55, 'reports_operation_log'),
(56, 'reports_operation_tips'),
(57, 'reports_communications_efficiency'),
(58, 'reports_message_sending_log'),
(59, 'reports_antifraud_restaurants'),
(60, 'reports_antifraud_waiters'),
(61, 'reports_dangerous_operations'),
(62, 'notification_dangerous_operations'),
(63, 'notification_feedback'),
(64, 'antifraud_settings'),
(65, 'antifraud_grey_list'),
(66, 'antifraud_white_list'),
(67, 'antifraud_black_list'),
(68, 'antifraud_block_list'),
(69, 'settings_pl_dishes_coefficients'),
(70, 'stock'),
(71, 'stock_promo_bonuses'),
(72, 'stock_corporate_catering'),
(73, 'stock_basic'),
(74, 'stock_happy_hour'),
(75, 'stock_birthday'),
(76, 'stock_registration_bonus'),
(77, 'stock_stamps'),
(78, 'stock_n_dish_present'),
(79, 'stock_bring_friend'),
(80, 'stock_special_price_combo'),
(81, 'stock_combo_discount'),
(82, 'stock_season_pass'),
(83, 'stock_information_campaign'),
(84, 'stock_check_discount_currency'),
(85, 'stock_check_discount_percent'),
(86, 'stock_dish_discount_currency'),
(87, 'stock_dish_discount_percent'),
(88, 'stock_dish_present'),
(89, 'stock_dish_special_price'),
(90, 'stock_bonus_points'),
(91, 'stock_check_bonus_points'),
(92, 'stock_dish_bonus_points'),
(93, 'stock_rank_bonus_points'),
(94, 'stock_basic_promo_code')
ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name;

INSERT INTO public.product_feature_access(product_id, feature_id, access_type, access_restriction_type, detail) VALUES
(1, 4, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(2, 4, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(4, 4, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(5, 4, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(1, 12, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Pro и выше'),
(1, 14, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(2, 14, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(1, 17, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Pro и выше'),
(1, 19, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Pro и выше'),
(1, 20, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Pro и выше'),
(1, 21, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Pro и выше'),
(1, 22, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Pro и выше'),
(1, 23, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(2, 23, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(1, 25, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(2, 25, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(4, 25, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(5, 25, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(1, 26, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Pro и выше'),
(4, 26, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Pro и выше'),
(1, 27, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Pro и выше'),
(4, 27, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Pro и выше'),
(1, 28, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Pro и выше'),
(1, 29, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Pro и выше'),
(1, 33, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(2, 33, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(1, 36, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Pro и выше'),
(4, 36, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Pro и выше'),
(1, 37, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Pro и выше'),
(4, 37, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Pro и выше'),
(1, 38, 'hidden', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(2, 38, 'hidden', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(1, 40, 'disable', 'tariff_not_enough', 'Данный отчет доступен только для сетевых организаций'),
(2, 40, 'disable', 'tariff_not_enough', 'Данный отчет доступен только для сетевых организаций'),
(3, 40, 'disable', 'tariff_not_enough', 'Данный отчет доступен только для сетевых организаций'),
(4, 40, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Pro и выше'),
(1, 41, 'hidden', 'tariff_not_enough', 'Доступно на лицензии с уровнем Pro и выше'),
(4, 41, 'hidden', 'tariff_not_enough', 'Доступно на лицензии с уровнем Pro и выше'),
(1, 42, 'hidden', 'tariff_not_enough', 'Доступно на лицензии с уровнем Pro и выше'),
(4, 42, 'hidden', 'tariff_not_enough', 'Доступно на лицензии с уровнем Pro и выше'),
(1, 43, 'hidden', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(2, 43, 'hidden', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(4, 43, 'hidden', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(5, 43, 'hidden', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(1, 44, 'hidden', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(2, 44, 'hidden', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(4, 44, 'hidden', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(5, 44, 'hidden', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(1, 45, 'hidden', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(2, 45, 'hidden', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(4, 45, 'hidden', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(5, 45, 'hidden', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(1, 48, 'hidden', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(2, 48, 'hidden', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(4, 48, 'hidden', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(5, 48, 'hidden', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(1, 49, 'hidden', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(2, 49, 'hidden', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(4, 49, 'hidden', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(5, 49, 'hidden', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(1, 52, 'hidden', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(2, 52, 'hidden', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(4, 52, 'hidden', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(5, 52, 'hidden', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(1, 54, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Pro и выше'),
(4, 54, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Pro и выше'),
(1, 57, 'hidden', 'tariff_not_enough', 'Доступно на лицензии с уровнем Pro и выше'),
(4, 57, 'hidden', 'tariff_not_enough', 'Доступно на лицензии с уровнем Pro и выше'),
(1, 59, 'hidden', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(2, 59, 'hidden', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(4, 59, 'hidden', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(5, 59, 'hidden', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(1, 60, 'hidden', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(2, 60, 'hidden', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(4, 60, 'hidden', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(5, 60, 'hidden', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(1, 62, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(2, 62, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(4, 62, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(5, 62, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(1, 65, 'hidden', 'tariff_not_enough', 'Доступно на лицензии с уровнем Pro и выше'),
(4, 65, 'hidden', 'tariff_not_enough', 'Доступно на лицензии с уровнем Pro и выше'),
(1, 71, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(2, 71, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(4, 71, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(5, 71, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(1, 72, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(2, 72, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(4, 72, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(5, 72, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(1, 74, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Pro и выше'),
(4, 74, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Pro и выше'),
(1, 75, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Pro и выше'),
(4, 75, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Pro и выше'),
(1, 77, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Pro и выше'),
(4, 77, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Pro и выше'),
(1, 78, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Pro и выше'),
(4, 78, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Pro и выше'),
(1, 79, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Pro и выше'),
(4, 79, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Pro и выше'),
(1, 82, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(2, 82, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(4, 82, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(5, 82, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(1, 93, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Pro и выше'),
(4, 93, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Pro и выше'),
(1, 94, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(2, 94, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(4, 94, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max'),
(5, 94, 'disable', 'tariff_not_enough', 'Доступно на лицензии с уровнем Max')
ON CONFLICT (product_id, feature_id) DO UPDATE SET access_type=EXCLUDED.access_type, access_restriction_type=EXCLUDED.access_restriction_type, detail=EXCLUDED.detail;";

        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(Sql);
        }
    }
}
